In [39]:
import numpy as np

In [40]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [41]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
mean_a = np.mean(a, axis = 0)

In [68]:
mean_a

array([2. , 8.4])

In [69]:
a_centered = a - mean_a

In [70]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [71]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [72]:
a_centered_sp

8.0

In [73]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

In [74]:
np.cov(a.T)[0, 1]

2.0